name: eslint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        cd flora/flora/
        npm
    - name: Run ESLint
      run: npx eslint "flora/flora/src/**"
